# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6797578872ee2c5ea59b4d703b9fcfe604eedb5ad52697ecdeb5838435837a8dfd690f22f828c82949f496ce107f491b16f8bc63732c9f9839fa602298002845

test:
  secret_key_base: a6fc44b4ca47094ce00c07d4303c914abf36f674ddd7da39acedd4be4734e0ba20c6172be234f9e8fbba106ac04848983ef890b9451f777cae75e1fbdf376f65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
